export type PropsBaseRadiusV = '' | 'circle' | 'round' | 'ellipse' | 'none'
export const propsBaseRadius:Array<PropsBaseRadiusV> = ['', 'circle', 'round', 'ellipse', 'none']
export type PropsBaseSizeV = '' | 'sm' | 'md' | 'lg'
export const propsBaseSize:Array<PropsBaseSizeV> = ['', 'sm', 'md', 'lg']
export type PropsBaseStateV = '' | 'primary' | 'success' | 'warning' | 'danger' | 'info'
export const propsBaseState:Array<PropsBaseStateV> = ['', 'primary', 'success', 'warning', 'danger', 'info']
export type PropsBtnGroupShapeV = '' | 'tight' | 'auto'
export const propsBtnGroupShape:Array<PropsBtnGroupShapeV> = ['', 'tight', 'auto']
export type PropsBtnShapeV = '' | 'ghost' | 'text'
export const propsBtnShape:Array<PropsBtnShapeV> = ['', 'ghost', 'text']
export type PropsBtnTypeV = 'submit' | 'button' | 'reset'
export const propsBtnType:Array<PropsBtnTypeV> = ['submit', 'button', 'reset']
export type PropsCallKitShapeV = '' | 'wx' | 'meet'
export const propsCallKitShape:Array<PropsCallKitShapeV> = ['', 'wx', 'meet']
export type PropsFlexV = '' | 'row' | 'col'
export const propsFlex:Array<PropsFlexV> = ['', 'row', 'col']
export type PropsFlexAlignV = '' | 'start' | 'end' | 'center' | 'stretch' | 'around' | 'between'
export const propsFlexAlign:Array<PropsFlexAlignV> = ['', 'start', 'end', 'center', 'stretch', 'around', 'between']
export type PropsFlexJustifyV = '' | 'start' | 'end' | 'center' | 'stretch' | 'around' | 'between' | 'evenly'
export const propsFlexJustify:Array<PropsFlexJustifyV> = ['', 'start', 'end', 'center', 'stretch', 'around', 'between', 'evenly']
export type PropsFlexSelfV = '' | 'start' | 'end' | 'center' | 'stretch'
export const propsFlexSelf:Array<PropsFlexSelfV> = ['', 'start', 'end', 'center', 'stretch']