export const EventUpdate = 'update:modelValue'
export const EventUpdateMc = 'update:mc'
export const EventChange = 'change'
export const EventSearch = 'search'
export const EventClick = 'click'
export const EventSelect = 'selected'
export const EventLeave = 'leave'